language = "en"
device = "pipewire"
use_gpu_fast = false
use_gpu_acc = false
speech_probability = 0.5
max_silence_chunks = 12
dump_audio = false
min_window_secs = 4.0
max_window_secs = 10.0
min_phrase_secs = 1.6
max_phrase_secs = 12.0
