[rules]
"доброго" = ""
"дня" = ""
"мене" = ""
"завод" = ""
"дмитрий" = ""
"до" = ""
"бого" = ""
"звуть" = ""
"тиметрі" = ""
"і" = ""
"я" = ""
"дуже" = ""
"сильно" = ""
"полюбляю" = ""
"цю" = ""
"роботу" = ""
"ранку" = ""
"дмитрій" = ""
